### REINVENT4 TOML input ###
### Transfer Learning (TL) Run Mode ###

# General Options
run_type = "transfer_learning"
use_cuda = true
tb_logdir = "TensoBoard_TL"
json_out_config = "TL_input.json"

[parameters]
# TL Parameters
num_epochs = 35
save_every_n_epochs = 5
batch_size = 10
num_refs = 50
sample_batch_size = 100

# Reinvent molecule generator
input_model_file = "/home/grad/Desktop/pietro/denovo/r4/REINVENT4-main_1/REINVENT4-main/priors/reinvent.prior"
smiles_file = "/home/grad/Desktop/pietro/denovo/s4-for-de-novo-drug-design/deliverables(1)/deliverables/data/mapk1/setup-9/train.txt"
output_model_file = "2/TL_Reinvent_mapk1.model"

